apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mons.ddhq.com
spec:
  group: ddhq.com
  names:
    kind: mon
    plural: mons
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            message:
              type: string
            name:
              type: string
            options:
              properties:
                locked:
                  type: boolean
              type: object
            query:
              type: string
            tags:
              items:
                type: string
              type: array
            type:
              type: string
          type: object
        status:
          properties:
            id:
              format: int64
              type: integer
            phase:
              type: string
          type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
