apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: mon-controller
  namespace: tmon
spec:
  #generateSelector: true
  resyncPeriodSeconds: 30
  resources:
  - apiVersion: ddhq.com/v1
    resource: mons
  hooks:
    sync:
      webhook:
        url: http://mon-controller.tmon/sync
        timeout: 10s
    finalize:
      webhook:
        url: http://mon-controller.tmon/finalize
        timeout: 10s
