apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: monitors.datadoghq.datadoghq.com
spec:
  group: datadoghq.datadoghq.com
  names:
    kind: Monitor
    plural: monitors
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            message:
              type: string
            name:
              type: string
            options:
              properties:
                locked:
                  type: boolean
              type: object
            query:
              type: string
            tags:
              items:
                type: string
              type: array
            type:
              type: string
          type: object
        status:
          properties:
            id:
              format: int64
              type: integer
            phase:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
